#!/usr/bin/env bash
#
# mkvenv - bootstrap a Python vritual environement
#
# Usage: mkvenv
#
# Creates a Python virtual environment with some default pakages of my choice.

set -euo pipefail

PYTHON_VIRTUAL_ENV_DEFAULT_NAME="${PYTHON_VIRTUAL_ENV_DEFAULT_NAME:-venv}"

virtualenv "$PYTHON_VIRTUAL_ENV_DEFAULT_NAME"

source "$PYTHON_VIRTUAL_ENV_DEFAULT_NAME"/bin/activate

pip install \
	"catppuccin[pygments]" \
	"ipdb" \
	"ipython"
